import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_layout/header/Header";
import Footer from "./_layout/Footer";
// import Corousel from "./_components/Corousel";
// import { CartProvider } from "@mrvautin/react-shoppingcart";
import Providercart from "./provider/Providercart";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-right" containerClassName="mt-4" />
        <Providercart>
          <Header />
          {children}
          <Footer />
        </Providercart>
      </body>
    </html>
  );
}
